/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#161717",
        "on-primary": "#ffffff",
        "primary-container": "#2b2b2b",
        "on-primary-container": "#939292",
        "primary-fixed": "#e4e2e1",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#1b1c1c",
        "on-primary-fixed-variant": "#474746",
        "inverse-primary": "#c8c6c5",
        "secondary": "#8c4f10",
        "on-secondary": "#ffffff",
        "secondary-container": "#fdad67",
        "on-secondary-container": "#763f00",
        "secondary-fixed": "#ffdcc2",
        "secondary-fixed-dim": "#ffb77b",
        "on-secondary-fixed": "#2e1500",
        "on-secondary-fixed-variant": "#6d3a00",
        "tertiary": "#2e0c00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4f1a00",
        "on-tertiary-container": "#d47b52",
        "tertiary-fixed": "#ffdbcd",
        "tertiary-fixed-dim": "#ffb596",
        "on-tertiary-fixed": "#360f00",
        "on-tertiary-fixed-variant": "#76320f",
        "background": "#fbf9f5",
        "on-background": "#1b1c1a",
        "surface": "#fbf9f5",
        "on-surface": "#1b1c1a",
        "surface-dim": "#dbdad6",
        "surface-bright": "#fbf9f5",
        "surface-variant": "#e4e2de",
        "on-surface-variant": "#444748",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ef",
        "surface-container": "#efeeea",
        "surface-container-high": "#eae8e4",
        "surface-container-highest": "#e4e2de",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f0ed",
        "outline": "#747878",
        "outline-variant": "#c4c7c7",
        "surface-tint": "#5f5e5e",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "sm": "0.125rem",
        "DEFAULT": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "container-max": "1280px"
      },
      fontFamily: {
        "serif": ["Libre Caslon Text", "Georgia", "serif"],
        "display-lg": ["Libre Caslon Text", "Georgia", "serif"],
        "headline-lg": ["Libre Caslon Text", "Georgia", "serif"],
        "headline-lg-mobile": ["Libre Caslon Text", "Georgia", "serif"],
        "headline-md": ["Libre Caslon Text", "Georgia", "serif"],
        "title-lg": ["Work Sans", "sans-serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "label-md": ["Work Sans", "sans-serif"],
        "sans": ["Work Sans", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "headline-lg": ["40px", { "lineHeight": "48px", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "400" }],
        "headline-md": ["28px", { "lineHeight": "36px", "fontWeight": "400" }],
        "title-lg": ["20px", { "lineHeight": "28px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.08em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
